---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./actual/ks.yaml
  - ./excalidraw/ks.yaml
  - ./hajimari-todd/ks.yaml
  - ./hajimari-andy/ks.yaml
  - ./invidious-server/ks.yaml
  - ./libreddit/ks.yaml
  - ./miniflux/ks.yaml
  - ./n8n/ks.yaml
  - ./nitter/ks.yaml
  - ./obsidian-couchdb/ks.yaml
  - ./paperless/ks.yaml
  - ./teslamate/ks.yaml
  - ./theme-park/ks.yaml
  - ./whoogle/ks.yaml
