---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-cloudnative-pg
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: "./kubernetes/greyrock-ops/apps/database/cloudnative-pg/operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: greyrock-ops-kubernetes
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-cloudnative-pg-config
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  interval: 10m
  path: "./kubernetes/greyrock-ops/apps/database/cloudnative-pg/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: greyrock-ops-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-cloudnative-pg
    - name: cluster-apps-onepassword-connect
