---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-thanos
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/greyrock-ops/apps/monitoring/thanos/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: greyrock-ops-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-external-secrets-stores
    - name: cluster-apps-democratic-csi-local-path
    - name: cluster-apps-rook-ceph-cluster
