---
#
# SECRET* vars are encrypted with sops
#

# renovate: datasource=github-releases depName=vectordotdev/vector
vector_version: "v0.28.0"
vector_download_url: "https://github.com/vectordotdev/vector/releases/download/{{ vector_version }}/vector-{{ vector_version[1:] }}-x86_64-unknown-linux-musl.tar.gz"

vector_aggregator_addr: "10.45.0.2"
vector_aggregator_port: "6001"

docker_base_dir: /opt/docker
