---
ansible_host: '10.1.1.3'
ansible_python_interpreter: /usr/bin/python3
ansible_user: todd
tm_todd_laptop_user: tm-todd-laptop

#zfs setup
zfs_install_update: false
zfs_enable_nfs: true
zfs_manage_filesystem_permissions: true
zfs_enable_samba: false
zfs_enable_performance_tuning: false # Not idempotent
zfs_create_pools: true
zfs_create_filesystems: true
zfs_monitoring_capacity_threshold: 92
zfs_pools:
  - name: 'speedy'
    action: 'create'
    atime: 'off'
    ashift: 12
    xattr: sa
    compression: 'lz4'
    devices:
      - '/dev/disk/by-id/scsi-SATA_INTEL_SSDSC2BB80_PHWL52240391800RGN'
      - '/dev/disk/by-id/scsi-SATA_INTEL_SSDSC2BB80_PHWL522402DA800RGN'
      - '/dev/disk/by-id/scsi-SATA_INTEL_SSDSC2BB80_PHWL5034005A800RGN'
      - '/dev/disk/by-id/scsi-SATA_INTEL_SSDSC2BB80_PHWL4436048S800RGN'
      - '/dev/disk/by-id/scsi-SATA_INTEL_SSDSC2BB80_PHWL50340062800RGN'
    type: 'raidz2'
    state: 'present'
  - name: 'tank'
    action: 'create'
    atime: 'off'
    ashift: 12
    xattr: sa
    compression: 'lz4'
    devices:
      - '/dev/disk/by-id/scsi-SATA_WDC_WD140EFGX-68_9LHZ4GAG'
      - '/dev/disk/by-id/scsi-SATA_WDC_WD140EFGX-68_QGKAHABT'
    type: 'mirror'
    state: 'present'
  - name: 'tank'
    action: 'add'
    atime: 'off'
    ashift: 12
    compression: 'lz4'
    devices:
      - '/dev/disk/by-id/scsi-SATA_WDC_WD140EFGX-68_9LK8HS5G'
      - '/dev/disk/by-id/scsi-SATA_WDC_WD140EFGX-68_9MHV93NU'
    type: 'mirror'
    state: 'present'
  - name: 'tank'
    action: 'add'
    atime: 'off'
    ashift: 12
    compression: 'lz4'
    devices:
      - '/dev/disk/by-id/scsi-SATA_WDC_WD140EFGX-68_9LKTEV9G'
      - '/dev/disk/by-id/scsi-SATA_WDC_WD140EFGX-68_9LKLU6HG'
    type: 'mirror'
    state: 'present'
  - name: 'tank'
    action: 'add'
    atime: 'off'
    ashift: 12
    compression: 'lz4'
    devices:
      - '/dev/disk/by-id/scsi-SATA_WDC_WD140EFGX-68_9LK8EP0G'
      - '/dev/disk/by-id/scsi-SATA_WDC_WD140EFGX-68_9LK8HXKG'
    type: 'mirror'
    state: 'present'
zfs_filesystems:
  - name: backup
    pool: tank
    state: present
    recordsize: 1M
    owner: 568
    group: 100
    sharenfs: on
    mountpoint: /tank/backup/
  - name: media
    pool: tank
    state: present
    recordsize: 1M
    owner: 568
    group: 100
    sharenfs: on
    mountpoint: /tank/media/
  - name: documents
    pool: tank
    state: present
    owner: 568
    group: 65543
    sharenfs: on
    mountpoint: /tank/documents/
  - name: frigate
    pool: tank
    state: present
    recordsize: 1M
    owner: 65534
    group: 65534
    sharenfs: on
    mountpoint: /tank/frigate/
  - name: garage
    pool: tank
    state: present
    owner: 1000
    group: 1000
    mountpoint: /tank/garage/
  - name: garage
    pool: speedy
    state: present
    owner: 1000
    group: 1000
    mountpoint: /speedy/garage/
  - name: tm-todds-laptop
    pool: tank
    state: present
    logbias: throughput
    recordsize: 1M
    compression: zle
    quota: 3T
    sync: disabled
    mountpoint: /tank/tm-todds-laptop

zfs_enable_monitoring: true
zfs_monitoring_scrub_max_age: 8
zfs_pools_scrub_cron:
  minute: 0
  hour: 2
  day: '*'
  month: '28'
  weekday: '*'

# samba
samba_users:
  - name: "{{ tm_todd_laptop_user }}"
    password: "{{ tm_todd_laptop_pass }}"


samba_shares:
  - name: tm-todd-laptop
    comment: 'Share useable as a TimeMachine backup target on MacOS'
    vfs_objects:
      - name: acl_xattr
      - name: catia
      - name: fruit
        options:
          - name: time machine
            value: 'yes'
          - name: nfs_aces
            value: 'no'
          - name: zero_file_id
            value: 'yes'
      - name: streams_xattr
    path: /tank/tm-todds-laptop
    write_list: tm-todd-laptop
    owner: tm-todd-laptop
    group: timemachine
    public: 'no'
    guest_ok: 'no'
    browseable: 'no'
