---
clusterName: greyrock-ops

talosVersion: v1.3.4
kubernetesVersion: 1.26.1
endpoint: "https://greyrock-ops.private.greyrock.io:6443"

cniConfig:
  name: none

additionalApiServerCertSans:
  - ${clusterEndpointIP}

additionalMachineCertSans:
  - ${clusterEndpointIP}
  - greyrock-ops.private.greyrock.io

nodes:
  - hostname: k8s1.private.greyrock.io
    ipAddress: 10.1.1.4
    controlPlane: true
    installDisk: /dev/nvme0n1
    disableSearchDomain: true
    networkInterfaces:
      - interface: eth0
        dhcp: true
  - hostname: k8s2.private.greyrock.io
    ipAddress: 10.1.1.5
    controlPlane: true
    installDisk: /dev/nvme0n1
    disableSearchDomain: true
    networkInterfaces:
      - interface: eth0
        dhcp: true
  - hostname: k8s3.private.greyrock.io
    ipAddress: 10.1.1.6
    controlPlane: true
    installDisk: /dev/nvme0n1
    disableSearchDomain: true
    networkInterfaces:
      - interface: eth0
        dhcp: true
  - hostname: k8s4.private.greyrock.io
    ipAddress: 10.1.1.7
    controlPlane: false
    installDisk: /dev/sda
    disableSearchDomain: true
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vlans:
          - vlanId: 20
            dhcp: false
            addresses:
              - 10.1.2.7/24
  - hostname: k8s5.private.greyrock.io
    ipAddress: 10.1.1.8
    controlPlane: false
    installDisk: /dev/sda
    disableSearchDomain: true
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vlans:
          - vlanId: 20
            dhcp: false
            addresses:
              - 10.1.2.8/24
  - hostname: k8s6.private.greyrock.io
    ipAddress: 10.1.1.9
    controlPlane: false
    installDisk: /dev/sda
    disableSearchDomain: true
    networkInterfaces:
      - interface: eth0
        dhcp: true
        vlans:
          - vlanId: 20
            dhcp: false
            addresses:
              - 10.1.2.9/24

controlPlane:
  patches:
    - |-
      cluster:
        allowSchedulingOnMasters: false
        apiServer:
          extraArgs:
            feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
            oidc-client-id: ${oidcClientId}
            oidc-groups-claim: https://greyrock/groups
            oidc-groups-prefix: 'oidc:'
            oidc-issuer-url: ${oidcIssuerURL}
            oidc-username-claim: email
            oidc-username-prefix: 'oidc:'
        controllerManager:
          extraArgs:
            feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
        discovery:
          registries:
            service:
              disabled: true
        proxy:
          disabled: true
          extraArgs:
            feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
        scheduler:
          extraArgs:
            feature-gates: MixedProtocolLBService=true,EphemeralContainers=True
        extraManifests:
          - https://raw.githubusercontent.com/doonga/greyrock-ops/main/infrastructure/talos/greyrock-ops/rbac/oidc.yaml

      machine:
        files:
          - content: |
              [plugins]
                [plugins."io.containerd.grpc.v1.cri"]
                  enable_unprivileged_ports = true
                  enable_unprivileged_icmp = true
            path: /etc/cri/conf.d/20-customization.part
            op: create
        kubelet:
          extraArgs:
            feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true
            rotate-server-certificates: "true"
          nodeIP:
            validSubnets:
              - 10.1.1.0/24
        install:
          extraKernelArgs:
            - "talos.logging.kernel=udp://vector.greyrock.tech:6050/"
        logging:
          destinations:
            - endpoint: "udp://vector.greyrock.tech:6051/"
              format: json_lines
        network:
          extraHostEntries:
            - ip: ${clusterEndpointIP}
              aliases:
                - greyrock-ops.private.greyrock.io
        sysctls:
          fs.inotify.max_user_watches: "1048576"
          fs.inotify.max_user_instances: "8192"
        time:
          disabled: false
          servers:
            - ntp.greyrock.io
    - |-
      - op: remove
        path: /cluster/apiServer/admissionControl

worker:
  patches:
    - |-
      machine:
        files:
          - content: |
              [plugins]
                [plugins."io.containerd.grpc.v1.cri"]
                  enable_unprivileged_ports = true
                  enable_unprivileged_icmp = true
            path: /etc/cri/conf.d/20-customization.part
            op: create
        kubelet:
          extraArgs:
            feature-gates: GracefulNodeShutdown=true,MixedProtocolLBService=true
            rotate-server-certificates: "true"
          nodeIP:
            validSubnets:
              - 10.1.1.0/24
        install:
          extraKernelArgs:
            - "talos.logging.kernel=udp://vector.greyrock.tech:6050/"
        logging:
          destinations:
            - endpoint: "udp://vector.greyrock.tech:6051/"
              format: json_lines
        network:
          extraHostEntries:
            - ip: ${clusterEndpointIP}
              aliases:
                - greyrock-ops.private.greyrock.io
        sysctls:
          fs.inotify.max_user_watches: "1048576"
          fs.inotify.max_user_instances: "8192"
        time:
          disabled: false
          servers:
            - ntp.greyrock.io
