---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-rook-ceph
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/greyrock-ops/apps/rook-ceph/rook-ceph/operator"
  prune: true
  sourceRef:
    kind: GitRepository
    name: greyrock-ops-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-csi-addons-controller-manager
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-rook-ceph-cluster
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/greyrock-ops/apps/rook-ceph/rook-ceph/cluster"
  prune: true
  sourceRef:
    kind: GitRepository
    name: greyrock-ops-kubernetes
  wait: true
  dependsOn:
    - name: cluster-apps-rook-ceph
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-rook-ceph-addons
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/greyrock-ops/apps/rook-ceph/rook-ceph/add-ons"
  prune: true
  sourceRef:
    kind: GitRepository
    name: greyrock-ops-kubernetes
  wait: false
  dependsOn:
    - name: cluster-apps-rook-ceph-cluster
