---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: blocky
  namespace: flux-system
spec:
  targetNamespace: network
  dependsOn:
    - name: external-secrets-stores
    - name: dragonfly-cluster
    - name: crunchy-postgres-operator-cluster
    - name: crunchy-postgres-operator-secretstore
  interval: 10m
  path: ./kubernetes/utility/apps/network/blocky/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: greyrock-ops-kubernetes
  wait: false
